### ISSUE TITLE
Example does not work?

### ISSUE THREAD

**Issue by chozabu** [liuwenchao/ajax-seo#2]
First up, thanks for this! It gives me a much better idea of the right way to use phantomjs

First issue I encountered is the example command `$ curl http://localhost:8888/page#!/id/12 --header Host:localhost:3000` - the `!` is interperted by bash as part of `history` - this is fixed by running `$ curl http://localhost:8888/page#\!/id/12 --header Host:localhost:3000` - note `\!`

after that - it still seems not to work, but has given me enough pointers, I should be able to fix it up for my situation!

**Comment by liuwenchao** [comment]
:+1:  let me know.
